#!/usr/bin/env python

from py2neo import Graph
from sys import argv
from os import environ

auth = environ["NEO4J_USERNAME"] + ":" + environ["NEO4J_PASSWORD"]
uri = "http://" + auth + "@localhost:7474/db/data"
graph = Graph(uri)

if len(argv) > 1 and argv[1] != 'show':
    command = 'MATCH (n) DELETE n' if argv[1] == 'drop' else argv[1]
    graph.cypher.execute(command)

print graph.cypher.execute('MATCH (n) RETURN n')
